version: 0.2

phases:
    install:
      runtime-versions:
        nodejs: 10
      commands:
      - cd frontend-master
      - npm install -g @angular/cli
      - npm install --save-dev @angular-devkit/build-angular
      - cd ..
    build:
      commands:
	- cd frontend-master
        - ng build --prod
	- cd ..
    post_build:
      commands:
        - aws s3 cp frontend-master/dist/doggywood 
s3://doggywood-veterinary --recursive
  
