version: 0.2

phases:
    install:
      runtime-versions:
        nodejs: 10
      commands:
      - npm install -g @angular/cli
      - npm install --save-dev @angular-devkit/build-angular
    build:
      commands:
        - ng build --prod
    post_build:
      commands:
        - aws s3 cp dist/doggywood s3://doggywood-veterinary --recursive
  